name: Lint
run-name: Checking linting against ${{ github.actor }} push

on:
  push:
    paths:
      - 'pyrorl/envs/*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: cd ${{ github.workspace }}
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}