name: Automated Building and Testing
run-name: ${{ github.actor }} pushed code
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start automated building and testing!"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python -m pip install setuptools wheel
      - run: cd ${{ github.workspace }}
      - run: cd wildfire_evac
      - run: ls
      - run: python setup.py sdist
      - run: python -m pip install -e .
