name: Automated Building and Testing
run-name: ${{ github.actor }} pushed code
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing this initial command"
